name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4 # Updated to the latest version
        with:
          persist-credentials: false

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v4 # Updated to the latest version
        with:
          node-version: 20 # Explicitly specify Node.js 20

      - name: Install dependencies 📦
        run: npm install

      - name: Build the project 🛠️
        run: npm run build

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the correct input 'token'
          branch: gh-pages
          folder: build
